### ISSUE TITLE
./install.bash: line 56: /root/.config/firefox.conf: No such file or directory

### ISSUE THREAD

**Issue by romulasry** [lebensterben/awesome-clear-linux#13]
./install.bash: line 56: /root/.config/firefox.conf: No such file or directory

Bug?

I used: sudo ./install.bash

When I use ./install.bash then put in the password I get:

./configure: line 7357: ffbuild/config.fate: Permission denied
./configure: line 7364: ffbuild/config.mak: Permission denied
./configure: line 593: ffbuild/config.mak: Permission denied

I set the file permissions to executable btw.

**Comment by lebensterben** [comment]
Don't you read the source code before running it?

https://github.com/lebensterben/awesome-clear-linux/blob/7c6053e12b25254d600c32ce05ae7ab70ba3c166/h264-firefox/install.bash#L8

This script is not intended to be run as sudo. When it needs root privilege, it asks for it.

**Comment by romulasry** [comment]
I used: sudo ./install.bash

When I use ./install.bash then put in the password I get:

./configure: line 7357: ffbuild/config.fate: Permission denied
./configure: line 7364: ffbuild/config.mak: Permission denied
./configure: line 593: ffbuild/config.mak: Permission denied

**Comment by lebensterben** [comment]
remove the contents of your working directory and try again
