### ISSUE TITLE
./install.bash does not work (used without sudo)!

### ISSUE THREAD

**Issue by romulasry** [lebensterben/awesome-clear-linux#14]
[33m⏳ Install the following dependencies: 'c-basic', 'devpkg-libva', and 'git' ...[m
Loading required manifests...
3 bundles were already installed
[33m⏳ Get latest FFmpeg source repository ...[m
[33m⏳ Checkout the latest non-dev release ...[m
[33m⏳ Building ...[m
[32m If the installation is successful, it would be available under [33m/opt/ffmpeg[32m.[m

install prefix            /opt/ffmpeg
source path               .
C compiler                gcc
C library                 glibc
ARCH                      x86 (generic)
big-endian                no
runtime cpu detection     yes
standalone assembly       yes
x86 assembler             nasm
MMX enabled               yes
MMXEXT enabled            yes
3DNow! enabled            yes
3DNow! extended enabled   yes
SSE enabled               yes
SSSE3 enabled             yes
AESNI enabled             yes
AVX enabled               yes
AVX2 enabled              yes
AVX-512 enabled           yes
XOP enabled               yes
FMA3 enabled              yes
FMA4 enabled              yes
i686 features enabled     yes
CMOV is fast              yes
EBX available             yes
EBP available             yes
debug symbols             yes
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    yes
postprocessing support    no
network support           yes
threading support         pthreads
safe bitstream reader     yes
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          no
makeinfo supports HTML    no

External libraries:
iconv                   zlib

External libraries providing hardware acceleration:
cuda_llvm               v4l2_m2m                vaapi

Libraries:
avcodec                 avformat                swscale
avdevice                avutil
avfilter                swresample

Programs:
ffmpeg                  ffprobe

Enabled decoders:
aac                     flac                    pgm
aac_fixed               flashsv                 pgmyuv
aac_latm                flashsv2                pgssub
aasc                    flic                    pictor
ac3                     flv                     pixlet
ac3_fixed               fmvc                    pjs
acelp_kelvin            fourxm                  png
adpcm_4xm               fraps                   ppm
adpcm_adx               frwu                    prores
adpcm_afc               g2m                     prosumer
adpcm_agm               g723_1                  psd
adpcm_aica              g729                    ptx
adpcm_argo              gdv                     qcelp
adpcm_ct                gif                     qdm2
adpcm_dtk               gremlin_dpcm            qdmc
adpcm_ea                gsm                     qdraw
adpcm_ea_maxis_xa       gsm_ms                  qpeg
adpcm_ea_r1             h261                    qtrle
adpcm_ea_r2             h263                    r10k
adpcm_ea_r3             h263_v4l2m2m            r210
adpcm_ea_xas            h263i                   ra_144
adpcm_g722              h263p                   ra_288
adpcm_g726              h264                    ralf
adpcm_g726le            h264_v4l2m2m            rasc
adpcm_ima_alp           hap                     rawvideo
adpcm_ima_amv           hca                     realtext
adpcm_ima_apc           hcom                    rl2
adpcm_ima_apm           hevc                    roq
adpcm_ima_cunning       hevc_v4l2m2m            roq_dpcm
adpcm_ima_dat4          hnm4_video              rpza
adpcm_ima_dk3           hq_hqa                  rscc
adpcm_ima_dk4           hqx                     rv10
adpcm_ima_ea_eacs       huffyuv                 rv20
adpcm_ima_ea_sead       hymt                    rv30
adpcm_ima_iss           iac                     rv40
adpcm_ima_mtf           idcin                   s302m
adpcm_ima_oki           idf                     sami
adpcm_ima_qt            iff_ilbm                sanm
adpcm_ima_rad           ilbc                    sbc
adpcm_ima_smjpeg        imc                     scpr
adpcm_ima_ssi           imm4                    screenpresso
adpcm_ima_wav           imm5                    sdx2_dpcm
adpcm_ima_ws            indeo2                  sgi
adpcm_ms                indeo3                  sgirle
adpcm_mtaf              indeo4                  sheervideo
adpcm_psx               indeo5                  shorten
adpcm_sbpro_2           interplay_acm           sipr
adpcm_sbpro_3           interplay_dpcm          siren
adpcm_sbpro_4           interplay_video         smackaud
adpcm_swf               jacosub                 smacker
adpcm_thp               jpeg2000                smc
adpcm_thp_le            jpegls                  smvjpeg
adpcm_vima              jv                      snow
adpcm_xa                kgv1                    sol_dpcm
adpcm_yamaha            kmvc                    sonic
adpcm_zork              lagarith                sp5x
agm                     loco                    speedhq
aic                     lscr                    srgc
alac                    m101                    srt
alias_pix               mace3                   ssa
als                     mace6                   stl
amrnb                   magicyuv                subrip
amrwb                   mdec                    subviewer
amv                     metasound               subviewer1
anm                     microdvd                sunrast
ansi                    mimic                   svq1
ape                     mjpeg                   svq3
apng                    mjpegb                  tak
aptx                    mlp                     targa
aptx_hd                 mmvideo                 targa_y216
arbc                    motionpixels            tdsc
ass                     movtext                 text
asv1                    mp1                     theora
asv2                    mp1float                thp
atrac1                  mp2                     tiertexseqvideo
atrac3                  mp2float                tiff
atrac3al                mp3                     tmv
atrac3p                 mp3adu                  truehd
atrac3pal               mp3adufloat             truemotion1
atrac9                  mp3float                truemotion2
aura                    mp3on4                  truemotion2rt
aura2                   mp3on4float             truespeech
avrn                    mpc7                    tscc
avrp                    mpc8                    tscc2
avs                     mpeg1_v4l2m2m           tta
avui                    mpeg1video              twinvq
ayuv                    mpeg2_v4l2m2m           txd
bethsoftvid             mpeg2video              ulti
bfi                     mpeg4                   utvideo
bink                    mpeg4_v4l2m2m           v210
binkaudio_dct           mpegvideo               v210x
binkaudio_rdft          mpl2                    v308
bintext                 msa1                    v408
bitpacked               mscc                    v410
bmp                     msmpeg4v1               vb
bmv_audio               msmpeg4v2               vble
bmv_video               msmpeg4v3               vc1
brender_pix             msrle                   vc1_v4l2m2m
c93                     mss1                    vc1image
cavs                    mss2                    vcr1
ccaption                msvideo1                vmdaudio
cdgraphics              mszh                    vmdvideo
cdtoons                 mts2                    vmnc
cdxl                    mv30                    vorbis
cfhd                    mvc1                    vp3
cinepak                 mvc2                    vp4
clearvideo              mvdv                    vp5
cljr                    mvha                    vp6
cllc                    mwsc                    vp6a
comfortnoise            mxpeg                   vp6f
cook                    nellymoser              vp7
cpia                    notchlc                 vp8
cscd                    nuv                     vp8_v4l2m2m
cyuv                    on2avc                  vp9
dca                     opus                    vp9_v4l2m2m
dds                     paf_audio               vplayer
derf_dpcm               paf_video               vqa
dfa                     pam                     wavpack
dirac                   pbm                     wcmv
dnxhd                   pcm_alaw                webp
dolby_e                 pcm_bluray              webvtt
dpx                     pcm_dvd                 wmalossless
dsd_lsbf                pcm_f16le               wmapro
dsd_lsbf_planar         pcm_f24le               wmav1
dsd_msbf                pcm_f32be               wmav2
dsd_msbf_planar         pcm_f32le               wmavoice
dsicinaudio             pcm_f64be               wmv1
dsicinvideo             pcm_f64le               wmv2
dss_sp                  pcm_lxf                 wmv3
dst                     pcm_mulaw               wmv3image
dvaudio                 pcm_s16be               wnv1
dvbsub                  pcm_s16be_planar        wrapped_avframe
dvdsub                  pcm_s16le               ws_snd1
dvvideo                 pcm_s16le_planar        xan_dpcm
dxa                     pcm_s24be               xan_wc3
dxtory                  pcm_s24daud             xan_wc4
dxv                     pcm_s24le               xbin
eac3                    pcm_s24le_planar        xbm
eacmv                   pcm_s32be               xface
eamad                   pcm_s32le               xl
eatgq                   pcm_s32le_planar        xma1
eatgv                   pcm_s64be               xma2
eatqi                   pcm_s64le               xpm
eightbps                pcm_s8                  xsub
eightsvx_exp            pcm_s8_planar           xwd
eightsvx_fib            pcm_u16be               y41p
escape124               pcm_u16le               ylc
escape130               pcm_u24be               yop
evrc                    pcm_u24le               yuv4
exr                     pcm_u32be               zero12v
ffv1                    pcm_u32le               zerocodec
ffvhuff                 pcm_u8                  zlib
ffwavesynth             pcm_vidc                zmbv
fic                     pcx
fits                    pfm

Enabled encoders:
a64multi                jpeg2000                ppm
a64multi5               jpegls                  prores
aac                     ljpeg                   prores_aw
ac3                     magicyuv                prores_ks
ac3_fixed               mjpeg                   qtrle
adpcm_adx               mjpeg_vaapi             r10k
adpcm_g722              mlp                     r210
adpcm_g726              movtext                 ra_144
adpcm_g726le            mp2                     rawvideo
adpcm_ima_qt            mp2fixed                roq
adpcm_ima_ssi           mpeg1video              roq_dpcm
adpcm_ima_wav           mpeg2_vaapi             rv10
adpcm_ms                mpeg2video              rv20
adpcm_swf               mpeg4                   s302m
adpcm_yamaha            mpeg4_v4l2m2m           sbc
alac                    msmpeg4v2               sgi
alias_pix               msmpeg4v3               snow
amv                     msvideo1                sonic
apng                    nellymoser              sonic_ls
aptx                    opus                    srt
aptx_hd                 pam                     ssa
ass                     pbm                     subrip
asv1                    pcm_alaw                sunrast
asv2                    pcm_dvd                 svq1
avrp                    pcm_f32be               targa
avui                    pcm_f32le               text
ayuv                    pcm_f64be               tiff
bmp                     pcm_f64le               truehd
cinepak                 pcm_mulaw               tta
cljr                    pcm_s16be               utvideo
comfortnoise            pcm_s16be_planar        v210
dca                     pcm_s16le               v308
dnxhd                   pcm_s16le_planar        v408
dpx                     pcm_s24be               v410
dvbsub                  pcm_s24daud             vc2
dvdsub                  pcm_s24le               vorbis
dvvideo                 pcm_s24le_planar        vp8_v4l2m2m
eac3                    pcm_s32be               vp8_vaapi
ffv1                    pcm_s32le               vp9_vaapi
ffvhuff                 pcm_s32le_planar        wavpack
fits                    pcm_s64be               webvtt
flac                    pcm_s64le               wmav1
flashsv                 pcm_s8                  wmav2
flashsv2                pcm_s8_planar           wmv1
flv                     pcm_u16be               wmv2
g723_1                  pcm_u16le               wrapped_avframe
gif                     pcm_u24be               xbm
h261                    pcm_u24le               xface
h263                    pcm_u32be               xsub
h263_v4l2m2m            pcm_u32le               xwd
h263p                   pcm_u8                  y41p
h264_v4l2m2m            pcm_vidc                yuv4
h264_vaapi              pcx                     zlib
hevc_v4l2m2m            pgm                     zmbv
hevc_vaapi              pgmyuv
huffyuv                 png

Enabled hwaccels:
h263_vaapi              mpeg2_vaapi             vp9_vaapi
h264_vaapi              mpeg4_vaapi             wmv3_vaapi
hevc_vaapi              vc1_vaapi
mjpeg_vaapi             vp8_vaapi

Enabled parsers:
aac                     dvdsub                  opus
aac_latm                flac                    png
ac3                     g723_1                  pnm
adx                     g729                    rv30
av1                     gif                     rv40
avs2                    gsm                     sbc
bmp                     h261                    sipr
cavsvideo               h263                    tak
cook                    h264                    vc1
dca                     hevc                    vorbis
dirac                   jpeg2000                vp3
dnxhd                   mjpeg                   vp8
dpx                     mlp                     vp9
dvaudio                 mpeg4video              webp
dvbsub                  mpegaudio               xma
dvd_nav                 mpegvideo

Enabled demuxers:
aa                      hnm                     pcm_s32be
aac                     ico                     pcm_s32le
ac3                     idcin                   pcm_s8
acm                     idf                     pcm_u16be
act                     iff                     pcm_u16le
adf                     ifv                     pcm_u24be
adp                     ilbc                    pcm_u24le
ads                     image2                  pcm_u32be
adx                     image2_alias_pix        pcm_u32le
aea                     image2_brender_pix      pcm_u8
afc                     image2pipe              pcm_vidc
aiff                    image_bmp_pipe          pjs
aix                     image_dds_pipe          pmp
alp                     image_dpx_pipe          pp_bnk
amr                     image_exr_pipe          pva
amrnb                   image_gif_pipe          pvf
amrwb                   image_j2k_pipe          qcp
anm                     image_jpeg_pipe         r3d
apc                     image_jpegls_pipe       rawvideo
ape                     image_pam_pipe          realtext
apm                     image_pbm_pipe          redspark
apng                    image_pcx_pipe          rl2
aptx                    image_pgm_pipe          rm
aptx_hd                 image_pgmyuv_pipe       roq
aqtitle                 image_pictor_pipe       rpl
argo_asf                image_png_pipe          rsd
asf                     image_ppm_pipe          rso
asf_o                   image_psd_pipe          rtp
ass                     image_qdraw_pipe        rtsp
ast                     image_sgi_pipe          s337m
au                      image_sunrast_pipe      sami
av1                     image_svg_pipe          sap
avi                     image_tiff_pipe         sbc
avr                     image_webp_pipe         sbg
avs                     image_xpm_pipe          scc
avs2                    image_xwd_pipe          sdp
bethsoftvid             ingenient               sdr2
bfi                     ipmovie                 sds
bfstm                   ircam                   sdx
bink                    iss                     segafilm
bintext                 iv8                     ser
bit                     ivf                     shorten
bmv                     ivr                     siff
boa                     jacosub                 sln
brstm                   jv                      smacker
c93                     kux                     smjpeg
caf                     kvag                    smush
cavsvideo               live_flv                sol
cdg                     lmlm4                   sox
cdxl                    loas                    spdif
cine                    lrc                     srt
codec2                  lvf                     stl
codec2raw               lxf                     str
concat                  m4v                     subviewer
data                    matroska                subviewer1
daud                    mgsts                   sup
dcstr                   microdvd                svag
derf                    mjpeg                   swf
dfa                     mjpeg_2000              tak
dhav                    mlp                     tedcaptions
dirac                   mlv                     thp
dnxhd                   mm                      threedostr
dsf                     mmf                     tiertexseq
dsicin                  mov                     tmv
dss                     mp3                     truehd
dts                     mpc                     tta
dtshd                   mpc8                    tty
dv                      mpegps                  txd
dvbsub                  mpegts                  ty
dvbtxt                  mpegtsraw               v210
dxa                     mpegvideo               v210x
ea                      mpjpeg                  vag
ea_cdata                mpl2                    vc1
eac3                    mpsub                   vc1t
epaf                    msf                     vividas
ffmetadata              msnwc_tcp               vivo
filmstrip               mtaf                    vmd
fits                    mtv                     vobsub
flac                    musx                    voc
flic                    mv                      vpk
flv                     mvi                     vplayer
fourxm                  mxf                     vqf
frm                     mxg                     w64
fsb                     nc                      wav
fwse                    nistsphere              wc3
g722                    nsp                     webm_dash_manifest
g723_1                  nsv                     webvtt
g726                    nut                     wsaud
g726le                  nuv                     wsd
g729                    ogg                     wsvqa
gdv                     oma                     wtv
genh                    paf                     wv
gif                     pcm_alaw                wve
gsm                     pcm_f32be               xa
gxf                     pcm_f32le               xbin
h261                    pcm_f64be               xmv
h263                    pcm_f64le               xvag
h264                    pcm_mulaw               xwma
hca                     pcm_s16be               yop
hcom                    pcm_s16le               yuv4mpegpipe
hevc                    pcm_s24be
hls                     pcm_s24le

Enabled muxers:
a64                     hls                     pcm_s32be
ac3                     ico                     pcm_s32le
adts                    ilbc                    pcm_s8
adx                     image2                  pcm_u16be
aiff                    image2pipe              pcm_u16le
amr                     ipod                    pcm_u24be
apng                    ircam                   pcm_u24le
aptx                    ismv                    pcm_u32be
aptx_hd                 ivf                     pcm_u32le
asf                     jacosub                 pcm_u8
asf_stream              kvag                    pcm_vidc
ass                     latm                    psp
ast                     lrc                     rawvideo
au                      m4v                     rm
avi                     matroska                roq
avm2                    matroska_audio          rso
avs2                    md5                     rtp
bit                     microdvd                rtp_mpegts
caf                     mjpeg                   rtsp
cavsvideo               mkvtimestamp_v2         sap
codec2                  mlp                     sbc
codec2raw               mmf                     scc
crc                     mov                     segafilm
dash                    mp2                     segment
data                    mp3                     singlejpeg
daud                    mp4                     smjpeg
dirac                   mpeg1system             smoothstreaming
dnxhd                   mpeg1vcd                sox
dts                     mpeg1video              spdif
dv                      mpeg2dvd                spx
eac3                    mpeg2svcd               srt
f4v                     mpeg2video              stream_segment
ffmetadata              mpeg2vob                streamhash
fifo                    mpegts                  sup
fifo_test               mpjpeg                  swf
filmstrip               mxf                     tee
fits                    mxf_d10                 tg2
flac                    mxf_opatom              tgp
flv                     null                    truehd
framecrc                nut                     tta
framehash               oga                     uncodedframecrc
framemd5                ogg                     vc1
g722                    ogv                     vc1t
g723_1                  oma                     voc
g726                    opus                    w64
g726le                  pcm_alaw                wav
gif                     pcm_f32be               webm
gsm                     pcm_f32le               webm_chunk
gxf                     pcm_f64be               webm_dash_manifest
h261                    pcm_f64le               webp
h263                    pcm_mulaw               webvtt
h264                    pcm_s16be               wtv
hash                    pcm_s16le               wv
hds                     pcm_s24be               yuv4mpegpipe
hevc                    pcm_s24le

Enabled protocols:
async                   http                    rtp
cache                   httpproxy               srtp
concat                  icecast                 subfile
crypto                  md5                     tcp
data                    mmsh                    tee
ffrtmphttp              mmst                    udp
file                    pipe                    udplite
ftp                     prompeg                 unix
gopher                  rtmp
hls                     rtmpt

Enabled filters:
abench                  deband                  palettegen
abitscope               deblock                 paletteuse
acompressor             decimate                pan
acontrast               deconvolve              perms
acopy                   dedot                   photosensitivity
acrossfade              deesser                 pixdesctest
acrossover              deflate                 pixscope
acrusher                deflicker               premultiply
acue                    deinterlace_vaapi       prewitt
addroi                  dejudder                procamp_vaapi
adeclick                denoise_vaapi           pseudocolor
adeclip                 derain                  psnr
adelay                  deshake                 qp
aderivative             despill                 random
adrawgraph              detelecine              readeia608
aecho                   dilation                readvitc
aemphasis               displace                realtime
aeval                   dnn_processing          remap
aevalsrc                doubleweave             removegrain
afade                   drawbox                 removelogo
afftdn                  drawgraph               replaygain
afftfilt                drawgrid                reverse
afifo                   drmeter                 rgbashift
afir                    dynaudnorm              rgbtestsrc
afirsrc                 earwax                  roberts
aformat                 ebur128                 rotate
agate                   edgedetect              scale
agraphmonitor           elbg                    scale2ref
ahistogram              entropy                 scale_vaapi
aiir                    equalizer               scdet
aintegral               erosion                 scroll
ainterleave             extractplanes           select
alimiter                extrastereo             selectivecolor
allpass                 fade                    sendcmd
allrgb                  fftdnoiz                separatefields
allyuv                  fftfilt                 setdar
aloop                   field                   setfield
alphaextract            fieldhint               setparams
alphamerge              fieldmatch              setpts
amerge                  fieldorder              setrange
ametadata               fifo                    setsar
amix                    fillborders             settb
amovie                  firequalizer            sharpness_vaapi
amplify                 flanger                 showcqt
amultiply               floodfill               showfreqs
anequalizer             format                  showinfo
anlmdn                  fps                     showpalette
anlms                   framepack               showspatial
anoisesrc               framerate               showspectrum
anull                   framestep               showspectrumpic
anullsink               freezedetect            showvolume
anullsrc                freezeframes            showwaves
apad                    gblur                   showwavespic
aperms                  geq                     shuffleframes
aphasemeter             gradfun                 shuffleplanes
aphaser                 gradients               sidechaincompress
apulsator               graphmonitor            sidechaingate
arealtime               greyedge                sidedata
aresample               haas                    sierpinski
areverse                haldclut                signalstats
arnndn                  haldclutsrc             silencedetect
aselect                 hdcd                    silenceremove
asendcmd                headphone               sinc
asetnsamples            hflip                   sine
asetpts                 highpass                smptebars
asetrate                highshelf               smptehdbars
asettb                  hilbert                 sobel
ashowinfo               histogram               spectrumsynth
asidedata               hqx                     split
asoftclip               hstack                  sr
asplit                  hue                     ssim
astats                  hwdownload              stereotools
astreamselect           hwmap                   stereowiden
asubboost               hwupload                streamselect
atadenoise              hysteresis              superequalizer
atempo                  idet                    surround
atrim                   il                      swaprect
avectorscope            inflate                 swapuv
avgblur                 interleave              tblend
axcorrelate             join                    telecine
bandpass                lagfun                  testsrc
bandreject              lenscorrection          testsrc2
bass                    life                    thistogram
bbox                    limiter                 threshold
bench                   loop                    thumbnail
bilateral               loudnorm                tile
biquad                  lowpass                 tlut2
bitplanenoise           lowshelf                tmedian
blackdetect             lumakey                 tmix
blend                   lut                     tonemap
bm3d                    lut1d                   tonemap_vaapi
bwdif                   lut2                    tpad
cas                     lut3d                   transpose
cellauto                lutrgb                  transpose_vaapi
channelmap              lutyuv                  treble
channelsplit            mandelbrot              tremolo
chorus                  maskedclamp             trim
chromahold              maskedmax               unpremultiply
chromakey               maskedmerge             unsharp
chromashift             maskedmin               untile
ciescope                maskedthreshold         v360
codecview               maskfun                 vectorscope
color                   mcompand                vflip
colorbalance            median                  vfrdet
colorchannelmixer       mergeplanes             vibrance
colorhold               mestimate               vibrato
colorkey                metadata                vignette
colorlevels             midequalizer            vmafmotion
colorspace              minterpolate            volume
compand                 mix                     volumedetect
compensationdelay       movie                   vstack
concat                  negate                  w3fdif
convolution             nlmeans                 waveform
convolve                noformat                weave
copy                    noise                   xbr
crop                    normalize               xfade
crossfeed               null                    xmedian
crystalizer             nullsink                xstack
cue                     nullsrc                 yadif
curves                  oscilloscope            yaepblur
datascope               overlay                 yuvtestsrc
dblur                   pad                     zoompan
dcshift                 pal100bars
dctdnoiz                pal75bars

Enabled bsfs:
aac_adtstoasc           h264_redundant_pps      null
av1_frame_merge         hapqa_extract           opus_metadata
av1_frame_split         hevc_metadata           pcm_rechunk
av1_metadata            hevc_mp4toannexb        prores_metadata
chomp                   imx_dump_header         remove_extradata
dca_core                mjpeg2jpeg              text2movsub
dump_extradata          mjpega_dump_header      trace_headers
eac3_core               mov2textsub             truehd_core
extract_extradata       mp3_header_decompress   vp9_metadata
filter_units            mpeg2_metadata          vp9_raw_reorder
h264_metadata           mpeg4_unpack_bframes    vp9_superframe
h264_mp4toannexb        noise                   vp9_superframe_split

Enabled indevs:
fbdev                   oss
lavfi                   v4l2

Enabled outdevs:
fbdev                   oss                     v4l2

License: LGPL version 2.1 or later
[31m Installation failed! Aborting...[m

Warning: Bundle "c-basic" is already installed, skipping it...
Warning: Bundle "devpkg-libva" is already installed, skipping it...
Warning: Bundle "git" is already installed, skipping it...
error: cannot open .git/FETCH_HEAD: Permission denied
HEAD is now at 6b6b9e593d Changelog: update
Press any key to continue ... ./configure: line 7357: ffbuild/config.fate: Permission denied
./configure: line 7364: ffbuild/config.mak: Permission denied
./configure: line 593: ffbuild/config.mak: Permission denied

**Comment by romulasry** [comment]
I deleted my FFmpeg folder and am trying again (compiling).

**Comment by romulasry** [comment]
Works but I get this:
Configuring dynamic linker configuration ...
include /etc/ld.so.conf.d/*.confgrep: /etc/ld.so.conf.d/ffmpeg.conf: No such file or directory

**Comment by lebensterben** [comment]
>Works but I get this: ...

@romulasry that comes from line 39 and should be ok

**Comment by lebensterben** [comment]
>Works but I get this: ...

@romulasry Fixed now. If you're unsure you can check line 47
