### ISSUE TITLE
Installation fails if folder /var/lib/dkms is missing

### ISSUE THREAD

**Issue by cattivik66** [lebensterben/awesome-clear-linux#25]
I've just installed clear-linux from scratch, and then executed scripts to deploy the drivers.

The second script (awesome-clear-linux/NVIDIA-Driver/install.bash)  throws an error as the folder /var/lib/dkms is missing.
Creating the folder and executing the installer again fixed the issue.

**Comment by lebensterben** [comment]
Have you restarted the computer before running the install script?

**Comment by BrunoBarrosXavier** [comment]
I was having the same issue.
Executing `mkdir /var/lib/dkms` seems to solve.

**Comment by lebensterben** [comment]
@BrunoBarrosXavier 

Have you restarted the computer before running the install script?

**Comment by BrunoBarrosXavier** [comment]
Yes. I restarted the computer after running the pre-install script.

I think it's a common issue:
[nvidia-drivers-installation-fails-due-to-dkms](https://community.clearlinux.org/t/nvidia-drivers-installation-fails-due-to-dkms/7027)

**Comment by lebensterben** [comment]
Okay. This did not happen to me. Maybe it's because the directory was created before.

Are you seeing this error on a new device that has no NVIDIA driver before?

**Comment by marioroy** [comment]
Thanks for this work. The driver installer creates ```lib64``` and ```lib32``` dirs.
```bash
$ ls /opt/nvidia/
bin  lib32  lib64  share
```
Currently, the [install.bash](https://github.com/lebensterben/awesome-clear-linux/blob/master/NVIDIA-Driver/install.bash#L37-L41) script assumes ```lib``` and ```lib32```. Shouldn't that be ```lib64``` and ```lib32```?
```text
/opt/nvidia/lib64
/opt/nvidia/lib32
```

**Comment by marioroy** [comment]
Please ignore my comment about about lib64. On a new install of Clear Linux, the NVIDIA installer mentions /opt/nvidia/lib will be used. On my prior installation, the NVIDIA installer used lib64.

**Comment by lebensterben** [comment]
@marioroy 
Thanks for your input.
If you wish you can make a quick PR to fix them. Otherwise I will fix them some time later.

**Comment by marioroy** [comment]
Your script is fine regarding lib, lib32, and lib64. I just installed using lib and lib32. The installer also makes lib64 which has xorg in it. So then that's all good. It was confusing to me seeing lib, lib32 in one part of your script and lib64 in another part.

I will update ffmpeg-on-clear-linux to check where the 64-bit libs reside in lib or lib64.

**Comment by marioroy** [comment]
The installer for CUDA places libraries under lib64. Well, it's your preference regarding using lib, lib32 or lib64, lib32.  On a newly installed Clear Linux, the paths must be created first or the installer will fail.  Along with /etc/ld.so.conf.d/nvidia.conf containing the 2 lib paths.

```bash
mkdir -p /var/lib/dkms
mkdir -p /opt/nvidia/lib
mkdir -p /opt/nvidia/lib32
```

**Comment by lebensterben** [comment]
It's not my preference.
I just followed the instructions from Clear Linux's official documentation.

**Comment by marioroy** [comment]
I too will follow the official documentation and update fmpeg-on-clear-linux. So lib and lib32 it is per Clear Linux's official documentation.

**Comment by morrolinux** [comment]
I can confirm the issue, the mentioned folders *must* be created manually on a newly installed system.
`/var/lib/dkms` in particular must be created before launching the install, otherwise the installation will fail.
@lebensterben can you please update the script? it's only one step away from perfect :)

**Comment by lebensterben** [comment]
@morrolinux 

In the latest commit /var/lib/dkms is checked (and created if doesn't exist) before installation.
