### ISSUE TITLE
CUDA gcc version

### ISSUE THREAD

**Issue by SPAstef** [lebensterben/awesome-clear-linux#4]
CUDA works with gcc-8 too, is there some particular reason you check for gcc7 in the script?

**Comment by lebensterben** [comment]
>CUDA works with gcc-8 too, is there some particular reason you check for gcc7 in the script?

@SPAstef 

This script hasn't been tested thoroughly.
It works with GCC 8 on 4.x kernel not 5.x kernels.

**Comment by SPAstef** [comment]
So Native clear Linux Is 4.x? Because it does work on mine...

**Comment by lebensterben** [comment]
>So Native clear Linux Is 4.x? Because it does work on mine...

@SPAstef what's your CUDA version?

**Comment by SPAstef** [comment]
CUDA 10.1 on GTX 1060, latest CLR build, latest Nvidia Drivers.

**Comment by lebensterben** [comment]
To be clear, you can freely install CUDA on either GCC 8 or GCC 7. But you can't compile CUDA 10.0 examples with GCC 8 on kernel 5.x (native)

**Comment by SPAstef** [comment]
Oh, I didn't try the examples, but FFMPEG and the code I write worked flawlessly
