### ISSUE TITLE
NVIDIA driver fails to build against 5.4.42-lts2019 and >=5.6.13-native kernels

### ISSUE THREAD

**Issue by peteonrails** [lebensterben/awesome-clear-linux#7]
Looks like a driver issue during DKMS compilation. Working on finding out more info.

**Comment by lebensterben** [comment]
>Looks like a driver issue during DKMS compilation. Working on finding out more info. 

@peteonrails What error message do you see?

**Comment by lebensterben** [comment]
@peteonrails does the problem still persist?

**Comment by insilications** [comment]
Possible fix here: https://github.com/lebensterben/awesome-clear-linux/issues/9

**Comment by lebensterben** [comment]
Closing this now since it can be built again.
---
Driver version: 450.57
Kernel version: 5.7.13-975.native
